// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyBrzwcUwKZTbypjdFLt2Vk4s0Ail03cw',
    appId: '1:98669513672:web:5640685e5db4fd8f4dcefd',
    messagingSenderId: '98669513672',
    projectId: 'finalprojectgks',
    authDomain: 'finalprojectgks.firebaseapp.com',
    storageBucket: 'finalprojectgks.appspot.com',
    measurementId: 'G-JN2EWQ99JT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnb1mgVlgDw8x59mONCHay3Cf2aXKaRXU',
    appId: '1:98669513672:android:9e302adb5e8748e54dcefd',
    messagingSenderId: '98669513672',
    projectId: 'finalprojectgks',
    storageBucket: 'finalprojectgks.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJeMhj7UusPmIsE9UqgrVtzPcBtaQZ0QA',
    appId: '1:98669513672:ios:4f834714beab39694dcefd',
    messagingSenderId: '98669513672',
    projectId: 'finalprojectgks',
    storageBucket: 'finalprojectgks.appspot.com',
    iosClientId: '98669513672-akqr66eg4pn90hbcj4m8ppe8bsbtve2k.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProjectFlutter',
  );
}
